# -- Site Configuration --
# Refer to the theme docs for more details about each of these parameters.
# https://jpanther.github.io/congo/docs/getting-started/

title = "Lery Monnerat"
baseURL = "http://localhost:1313/"
defaultContentLanguage = "fr"
#languageCode = "fr"
enableRobotsTXT = true
summaryLength = 0
theme="congo"

[[params.social]]
  icon  = "icon-github"
  title = "Github"
  url   = "https://github.com/lerymonnerat"

[[params.social]]
  icon  = "icon-linkedin"
  title = "Linkedin"
  url   = "https://www.linkedin.com/in/l%C3%A9ry-monnerat-5661b4297/"

[pagination]
  pagerSize = 10

[outputs]
  home = ["HTML", "RSS", "JSON"]
